(function(){
'use strict';
var transcriptState={items:[],counts:{total:0,needsReview:0,withOpenActions:0,failedProcessing:0},active:null,loaded:false,loading:false,error:'',lastLoadedAt:''};
var draftSignalState={drafts:[],loaded:false,error:''};
var navItems=[
  ['dashboard','⌂','Dashboard'],['chat','✦','General Chat'],['relationships','◎','Relationships'],['meetings','▣','Meetings'],['transcripts','≣','Transcripts'],
  ['communications','✉','Communications'],['email_intelligence','✉','Email Intelligence'],['opportunities','↗','Opportunities'],['tasks','✓','Tasks'],['drafts','✎','Drafts'],['intelligence','✦','Intelligence'],
  ['leads_employers','⌕','Scrape Employers'],['leads_partners','◇','Scrape Partners'],['settings','⚙','Settings'],['settings_templates','▤','Templates']
];
function safe(value){return typeof docSafe==='function'?docSafe(String(value==null?'':value)):String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function call(name){var fn=window[name];if(typeof fn==='function')return fn.apply(window,[].slice.call(arguments,1));}
function installShell(){
  var app=document.querySelector('.app');if(!app||document.getElementById('valPrimaryNav'))return;
  var nav=document.createElement('nav');nav.id='valPrimaryNav';nav.className='val-primary-nav';nav.setAttribute('aria-label','Primary navigation');
  nav.innerHTML='<div class="val-nav-brand"><span class="val-nav-mark">V</span><span><strong id="valNavBrand">VAL</strong><small>Command Center</small></span></div><div class="val-nav-items">'+navItems.map(function(n){var group=n[0]==='leads_employers'?'<div class="val-nav-group-label">Lead Scraper</div>':(n[0]==='settings'?'<div class="val-nav-group-label">Settings</div>':'');var child=/^leads_/.test(n[0])||n[0]==='settings_templates'?' child':'';return group+'<button class="val-nav-item'+(n[0]==='dashboard'?' active':'')+child+'" data-view="'+n[0]+'" onclick="commandCenterNavigate(\''+n[0]+'\')"><span class="val-nav-icon">'+n[1]+'</span><span>'+n[2]+'</span></button>';}).join('')+'</div><div class="val-nav-foot"><span id="valNavStatus">System ready</span></div>';
  app.insertBefore(nav,app.firstChild);
  var top=document.querySelector('.topbar');if(top){var b=document.createElement('button');b.className='val-mobile-nav';b.setAttribute('aria-label','Open navigation');b.innerHTML='☰';b.onclick=function(){nav.classList.toggle('open');};top.insertBefore(b,top.firstChild);}
  var center=document.querySelector('.center'),cmd=center&&center.querySelector('.cmd-area');if(center&&cmd){var view=document.createElement('section');view.id='valTranscriptView';view.className='val-transcript-view';center.insertBefore(view,cmd);}
  setTimeout(function(){var brand=document.getElementById('valNavBrand');if(brand&&window.VAL_CONFIG)brand.textContent=VAL_CONFIG.brandName||VAL_CONFIG.clientName||'VAL';},200);
  buildCommandCenter();loadTranscripts(false);loadDraftSignals(false);
}
function setActive(view){document.querySelectorAll('.val-nav-item').forEach(function(el){el.classList.toggle('active',el.getAttribute('data-view')===view);});var nav=document.getElementById('valPrimaryNav');if(nav)nav.classList.remove('open');}
function closeTranscriptView(){var view=document.getElementById('valTranscriptView');if(view)view.classList.remove('open');transcriptState.active=null;}
window.commandCenterNavigate=function(view){
  setActive(view);closeTranscriptView();
  if(view==='dashboard'){call('closeDetail');buildCommandCenter();return;}
  if(view==='transcripts'){openTranscripts();return;}
  var routes={chat:'openGeneralChat',relationships:'openRelationshipReview',meetings:'openMeetingBriefing',communications:'askComms',email_intelligence:'openEmailIntelligence',opportunities:'openOpportunityIntelligence',tasks:'openTaskBoard',drafts:'openDraftsPage',intelligence:'openPriorityReview',leads_employers:'openLeadIntelligence',leads_partners:'openPartnerIntelligence',settings:'openKeysPanel',settings_templates:'openTemplatesPage'};
  call(routes[view]||'closeDetail');
};
function listLine(label,value){return '<div class="val-mini-item"><strong>'+safe(label)+'</strong><span>'+safe(value)+'</span></div>';}
function loadDraftSignals(show){
  var fetcher=typeof apiFetch==='function'?apiFetch:function(url){return fetch(url,{credentials:'same-origin'}).then(function(r){return r.json();});};
  return fetcher((window.PROXY||'')+'/api/val/drafts').then(function(data){draftSignalState.drafts=Array.isArray(data.drafts)?data.drafts:[];draftSignalState.loaded=true;draftSignalState.error='';buildCommandCenter();return data;}).catch(function(e){draftSignalState.loaded=true;draftSignalState.error=e.message||String(e);if(show&&typeof addSys==='function')addSys('Drafts could not be loaded: '+draftSignalState.error);buildCommandCenter();});
}
function upcomingEvents(){return ([].concat((window.dashData&&dashData.appointments)||[],(window.dashData&&dashData.calendarEvents)||[])).filter(function(e){var d=new Date(e.startTime||e.start||e.date||0);return d>=new Date()&&!isNaN(d);}).sort(function(a,b){return new Date(a.startTime||a.start||a.date)-new Date(b.startTime||b.start||b.date);});}
function taskInfo(){var all=window.valTasks||((window.dashData&&dashData.tasks)||[]),open=all.filter(function(t){return !t.completed&&t.status!=='completed';}),now=new Date(),todayEnd=new Date();todayEnd.setHours(23,59,59,999);return{open:open,overdue:open.filter(function(t){return t.dueDate&&new Date(t.dueDate)<now;}),unscheduled:open.filter(function(t){return !t.scheduledStart&&!t.calendarEventId;}),scheduledToday:open.filter(function(t){var d=t.scheduledStart?new Date(t.scheduledStart):null;return d&&!isNaN(d)&&d>=now&&d<=todayEnd;})};}
function commandCard(kicker,title,copy,action,label,extra,priority){return '<article class="val-command-card'+(priority?' priority':'')+'"><div class="val-card-head"><div class="val-card-kicker">'+safe(kicker)+'</div>'+(extra&&extra.count!=null?'<span class="val-card-count">'+safe(extra.count)+'</span>':'')+'</div><h3>'+safe(title)+'</h3>'+(extra&&extra.html?'<div class="val-mini-list">'+extra.html+'</div>':'<p>'+safe(copy)+'</p>')+'<button class="val-card-action" onclick="'+action+'">'+safe(label)+'</button></article>';}
function buildCommandCenter(){
  var welcome=document.getElementById('centerWelcome');if(!welcome)return;
  var events=upcomingEvents(),tasks=taskInfo(),next=events[0],unread=Number((window.dashData&&dashData.followups)||0),pipeline=Number((window.dashData&&dashData.pipelineActive)||0),stalled=Number((window.dashData&&dashData.stalledDeals)||0);
  var priorityHtml='';if(next)priorityHtml+=listLine(next.title||next.summary||next.contactName||'Next meeting',new Date(next.startTime||next.start||next.date).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}));if(tasks.overdue.length)priorityHtml+=listLine(tasks.overdue[0].title||'Overdue commitment','Overdue');if(unread)priorityHtml+=listLine('Important conversations',unread+' unread');if(!priorityHtml)priorityHtml=listLine('No urgent exceptions detected','Review your day');
  var tr=transcriptState.items.slice(0,2),trHtml=tr.map(function(t){return listLine(t.title,t.status==='needs_review'?'Needs review':new Date(t.createdAt).toLocaleDateString());}).join('');
  var recapDrafts=draftSignalState.drafts.filter(function(d){return d.draftType==='meeting_recap'&&String(d.status||'draft')!=='approved'&&String(d.status||'draft')!=='sent';});
  var recentTranscriptTasks=(window.valTasks||((window.dashData&&dashData.tasks)||[])).filter(function(t){return t.transcriptId||t.sourceTranscriptId||/transcript/i.test(String(t.source||t.origin||''));}).slice(0,2);
  var recapHtml='';
  recapDrafts.slice(0,2).forEach(function(d){var ctx=d.sourceContext||{};recapHtml+=listLine(d.subject||'Meeting recap draft',ctx.meetingTitle||ctx.transcriptTitle||d.status||'Draft');});
  if(Number(transcriptState.counts.failedProcessing||0))recapHtml+=listLine('Failed transcript processing',transcriptState.counts.failedProcessing+' need attention');
  recentTranscriptTasks.forEach(function(t){recapHtml+=listLine(t.title||t.taskTitle||'Transcript task',t.dueDate||t.status||'created');});
  var html='<div class="cw-label">Executive Command Center</div><div class="cw-title">Today, clearly.</div><div class="cw-sub">The decisions, relationships, and commitments most likely to need your attention—without the dashboard noise.</div><div class="val-command-grid">';
  html+=commandCard("Today's Priorities",tasks.overdue.length?'Close the open loops first':'Your highest-leverage work is ready','VAL ranked today across meetings, communication, relationships, commitments, and revenue.','openPriorityReview()','Do It',{count:(tasks.overdue.length+unread+(stalled||0))+' signals',html:priorityHtml},true);
  html+=commandCard('Meetings',next?(next.title||next.summary||'Next meeting'):'No upcoming meeting',next?'Your next conversation is ready for context and preparation.':'Your connected calendar has no upcoming event.','openMeetingBriefing()','Prepare Briefing',{count:events.length+' upcoming'});
  html+=commandCard('Transcripts',transcriptState.error?'Unable to load transcripts':tr.length?'Recent conversations are in memory':'No transcripts received yet',transcriptState.error?'The transcript archive could not be reached. Open it to retry.':'Webhook transcripts, summaries, and open actions live together here.','openTranscripts()','View Transcripts',{count:transcriptState.error?'Needs attention':transcriptState.counts.needsReview+' to review',html:trHtml||''});
  html+=commandCard('Meeting Recaps & Drafts',recapDrafts.length?recapDrafts.length+' recap drafts need approval':'Recaps and transcript drafts are current',draftSignalState.error?'Draft signals could not be loaded.':'Review recap drafts, failed transcript processing, and tasks created from transcript intelligence.','openDraftsPage()','Review Drafts',{count:(recapDrafts.length+Number(transcriptState.counts.failedProcessing||0))+' items',html:recapHtml||''});
  var openLoopHtml='';tasks.unscheduled.slice(0,2).forEach(function(t){openLoopHtml+=listLine(t.title||'Unscheduled task',t.dueDate?'Due '+new Date(t.dueDate).toLocaleDateString():'Needs time block');});tasks.scheduledToday.slice(0,1).forEach(function(t){openLoopHtml+=listLine(t.title||'Scheduled task','Today '+new Date(t.scheduledStart).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}));});
  html+=commandCard('Open Loops',tasks.unscheduled.length?tasks.unscheduled.length+' tasks need calendar time':'Tasks have protected time blocks',tasks.overdue.length?tasks.overdue.length+' overdue tasks also need attention.':'Calendarized tasks protect time without creating meetings.','openTaskBoard()','Calendarize Tasks',{count:tasks.unscheduled.length+' unscheduled',html:openLoopHtml||''},tasks.overdue.length>0);
  html+=commandCard('Communications',unread?unread+' conversations need attention':'Your communication queue is clear','Review important threads, waiting-on-response items, and draft replies.','openEmailIntelligence()','Draft Reply',{count:unread+' unread'});
  html+=commandCard('Relationships','Keep valuable people from drifting','See who needs follow-up and why the relationship matters now.','openRelationshipReview()','Review');
  html+=commandCard('Opportunities',pipeline?pipeline+' active opportunities':'Review opportunity signals',stalled?stalled+' opportunities may be stalled.':'Pipeline and lead signals are ready for review.','openOpportunityIntelligence()','Open',{count:stalled+' stalled'});
  html+=commandCard('Tasks & Commitments',tasks.open.length?tasks.open.length+' open commitments':'No open commitments',tasks.overdue.length?tasks.overdue.length+' are overdue and should be resolved first.':'Promised follow-ups and action items are organized here.','openTaskBoard()','Create Task',{count:tasks.overdue.length+' overdue'});
  html+='</div>';welcome.innerHTML=html;welcome.style.display='block';
}
function loadTranscripts(show){
  var fetcher=typeof apiFetch==='function'?apiFetch:function(url){return fetch(url,{credentials:'same-origin'}).then(function(r){return r.json().catch(function(){return{};}).then(function(data){if(!r.ok)throw new Error(data.error||('Transcript request failed ('+r.status+')'));return data;});});};
  transcriptState.loading=true;transcriptState.error='';if(show)renderTranscriptLoading();
  return fetcher((window.PROXY||'')+'/api/val/transcripts?days=3650&limit=250').then(function(data){if(!data||data.ok===false||!Array.isArray(data.transcripts))throw new Error((data&&data.error)||'Transcript retrieval returned an invalid response.');transcriptState.items=data.transcripts;transcriptState.counts=data.counts||{total:data.transcripts.length,needsReview:0,withOpenActions:0};transcriptState.loaded=true;transcriptState.loading=false;transcriptState.error='';transcriptState.lastLoadedAt=new Date().toISOString();buildCommandCenter();if(show)renderTranscriptList();return data;}).catch(function(e){transcriptState.loaded=true;transcriptState.loading=false;transcriptState.error=e.message||String(e);buildCommandCenter();if(show)renderTranscriptError(transcriptState.error);throw e;});
}
window.openTranscripts=function(){setActive('transcripts');call('closeDetail');var welcome=document.getElementById('centerWelcome');if(welcome)welcome.style.display='none';var view=document.getElementById('valTranscriptView');if(view)view.classList.add('open');if(!transcriptState.loaded||transcriptState.error){loadTranscripts(true).catch(function(){});}else renderTranscriptList();};
function transcriptHeader(subtitle,back){return '<div class="val-view-head"><div><h2>Transcript Intelligence</h2><p>'+safe(subtitle)+'</p></div><div class="val-view-actions">'+(back?'<button class="val-ui-btn" onclick="renderTranscriptList()">Inbox</button>':'')+'<button class="val-ui-btn" onclick="renderTranscriptReviewQueue()">Review Queue</button><button class="val-ui-btn" onclick="openIntegrationStatus()">Webhook Setup</button><button class="val-ui-btn" '+(transcriptState.loading?'disabled':'')+' onclick="loadTranscripts(true).catch(function(){})">'+(transcriptState.loading?'Refreshing…':'Refresh')+'</button></div></div>';}
function renderTranscriptLoading(){var view=document.getElementById('valTranscriptView');if(view)view.innerHTML=transcriptHeader('Loading the durable transcript archive…')+'<div class="val-empty val-transcript-loading">Refreshing transcripts…</div>';}
window.renderTranscriptList=function(){
  transcriptState.active=null;var view=document.getElementById('valTranscriptView');if(!view)return;
  var c=transcriptState.counts,rows=transcriptState.items.map(function(t){var participants=(t.participants||[]).map(function(p){return p.matchedContactName||p.speakerNameRaw;}).filter(Boolean).join(', '),meta=[t.source,t.createdAt?new Date(t.createdAt).toLocaleString():'',participants].filter(Boolean).join(' · '),status=String(t.processingStatus||t.reviewStatus||t.status||'received').replace(/_/g,' '),summary=t.summary&&typeof t.summary==='object'?t.summary.executiveSummary:(t.summary||t.preview||'Summary pending.');return '<article class="val-transcript-row"><div class="val-transcript-copy"><div class="val-transcript-row-head"><h3>'+safe(t.title)+'</h3><span class="val-status '+(Number(t.reviewCount||0)?'review':'')+'">'+safe(status)+'</span></div><div class="val-transcript-meta">'+safe(meta)+'</div><p>'+safe(summary)+'</p><div class="val-transcript-action-count">'+Number(t.taskCount||t.openActionCount||0)+' tasks extracted · '+Number(t.reviewCount||0)+' review items · summary '+safe(t.summaryStatus||'legacy')+'</div></div><div class="val-transcript-actions"><button class="val-ui-btn primary" onclick="openTranscriptDetail(\''+safe(t.id)+'\')">Open Transcript</button><button class="val-ui-btn" onclick="transcriptAskFromList(\''+safe(t.id)+'\')">Ask VAL</button><button class="val-ui-btn" onclick="transcriptCreateTask(\''+safe(t.id)+'\')">Create Task</button><button class="val-ui-btn" onclick="transcriptDraftFollowUp(\''+safe(t.id)+'\')">Draft Follow-Up</button></div></article>';}).join('');
  view.innerHTML=transcriptHeader('Inbox · every transcript is saved, summarized, staged, and traceable before CRM action.')+'<div class="val-transcript-stats"><span class="val-transcript-stat"><strong>'+c.total+'</strong> received</span><span class="val-transcript-stat"><strong>'+c.needsReview+'</strong> need review</span><span class="val-transcript-stat"><strong>'+Number(c.withTasks||c.withOpenActions||0)+'</strong> with tasks</span></div><div class="val-transcript-list">'+(rows||'<div class="val-empty">No transcripts have arrived yet. The webhook is ready.</div>')+'</div>';
};
window.renderTranscriptReviewQueue=function(){var view=document.getElementById('valTranscriptView');if(!view)return;view.innerHTML=transcriptHeader('Loading review queue…',true)+'<div class="val-empty">Loading…</div>';var fetcher=typeof apiFetch==='function'?apiFetch:function(url){return fetch(url,{credentials:'same-origin'}).then(function(r){return r.json();});};fetcher((window.PROXY||'')+'/api/val/transcripts/review').then(function(d){var cards=[];(d.participants||[]).forEach(function(p){cards.push('<article class="val-review-card"><span class="val-status review">Participant match</span><h3>'+safe(p.speakerNameRaw)+'</h3><p>'+safe(p.matchReason)+' · '+Math.round(Number(p.matchConfidence||0)*100)+'% confidence</p><button class="val-ui-btn primary" onclick="approveTranscriptParticipant(\''+safe(p.participantId)+'\')">Approve Match</button></article>');});(d.tasks||[]).forEach(function(t){cards.push('<article class="val-review-card"><span class="val-status review">Task</span><h3>'+safe(t.taskTitle)+'</h3><p>'+safe(t.assignedToName||'Assignment unclear')+' · “'+safe(t.sourceQuote)+'”</p><button class="val-ui-btn primary" onclick="approveTranscriptTask(\''+safe(t.taskId)+'\')">Approve & Create</button></article>');});(d.contactUpdates||[]).forEach(function(u){cards.push('<article class="val-review-card"><span class="val-status review">Contact update</span><h3>'+safe(u.fieldToUpdate)+': '+safe(u.newValue)+'</h3><p>'+safe(u.reason)+' · “'+safe(u.sourceQuote)+'”</p><button class="val-ui-btn" onclick="approveTranscriptContactUpdate(\''+safe(u.updateId)+'\')">Approve Update</button></article>');});view.innerHTML=transcriptHeader('Review Queue · uncertainty stops here until a person decides.',true)+'<div class="val-review-grid">'+(cards.join('')||'<div class="val-empty">Nothing needs approval.</div>')+'</div>';}).catch(function(e){renderTranscriptError(e.message);});};
function renderTranscriptError(message){var view=document.getElementById('valTranscriptView');if(view)view.innerHTML=transcriptHeader('Transcript archive unavailable')+'<div class="val-empty val-transcript-error"><strong>Unable to load transcripts.</strong><br>Check the transcript retrieval endpoint or server logs.<br><small>'+safe(message)+'</small></div>';}
function normalizeList(items){return (Array.isArray(items)?items:[]).map(function(x){return typeof x==='string'?x:(x.title||x.text||x.summary||x.name||x.email||JSON.stringify(x));}).filter(Boolean);}
window.openTranscriptDetail=function(id){
  var view=document.getElementById('valTranscriptView');if(view)view.innerHTML='<div class="val-empty">Opening transcript…</div>';
  return (typeof apiFetch==='function'?apiFetch((window.PROXY||'')+'/api/val/transcripts/'+encodeURIComponent(id)):fetch('/api/val/transcripts/'+encodeURIComponent(id),{credentials:'same-origin'}).then(function(r){return r.json().then(function(data){if(!r.ok)throw new Error(data.error||'Transcript could not be opened.');return data;});})).then(function(data){if(!data.transcript)throw new Error(data.error||'Transcript could not be opened.');transcriptState.active=data.transcript;renderTranscriptDetail(data.transcript);return data.transcript;}).catch(function(e){renderTranscriptError(e.message);throw e;});
};
function detailList(items,empty){var arr=normalizeList(items);return arr.length?'<ul>'+arr.map(function(x){return '<li>'+safe(x)+'</li>';}).join('')+'</ul>':'<p>'+safe(empty)+'</p>';}
function draftRecipients(ctx){var r=ctx&&ctx.recipients;if(Array.isArray(r))return r.join(', ');return (ctx&&ctx.recipient)||(ctx&&ctx.recipientEmail)||'';}
function renderTranscriptDetail(t){
  var view=document.getElementById('valTranscriptView');if(!view)return;var meta=[t.contactName,t.source,t.createdAt?new Date(t.createdAt).toLocaleString():''].filter(Boolean).join(' · ');
  var s=t.summary&&typeof t.summary==='object'?t.summary:{executiveSummary:t.summary||''};
  var participants=(t.participants||[]).map(function(p){return (p.matchedContactName||p.speakerNameRaw)+' — '+Math.round(Number(p.matchConfidence||0)*100)+'% · '+p.matchReason+(p.needsReview?' [review]':'');});
  var tasks=(t.tasks||[]).map(function(x){return x.taskTitle+' — '+(x.status||'staged')+' · “'+x.sourceQuote+'”';});
  var createdTasks=(t.tasks||[]).filter(function(x){return String(x.status||'').toLowerCase()==='created';}).map(function(x){return x.taskTitle+' — '+(x.assignedToName||'VAL task system')+(x.dueDate?' · due '+x.dueDate:'');});
  var updates=(t.contactUpdates||[]).map(function(x){return x.fieldToUpdate+': '+x.newValue+' · “'+x.sourceQuote+'”';}),log=(t.actionLog||[]).map(function(x){return x.actionType+' — '+x.status+(x.errorMessage?' · '+x.errorMessage:'');});
  var status=['Processing: '+(t.processingStatus||t.status||'received'),'Summary: '+(t.summaryStatus||'pending'),'Review items: '+Number(t.reviewCount||0),'Tasks extracted: '+Number(t.taskCount||(t.tasks||[]).length)].join(' · ');
  var recap=(t.drafts||[]).find(function(d){return d.draftType==='meeting_recap';});
  var recapHtml=recap?'<div class="val-recap-preview"><strong>'+safe(recap.subject||'Meeting recap draft')+'</strong><p>'+safe((recap.body||'').slice(0,700))+'</p><small>Status: '+safe(recap.status||'draft')+(draftRecipients(recap.sourceContext)?' · Recipients: '+safe(draftRecipients(recap.sourceContext)):'')+'</small></div>':'<p>No recap draft has been created yet.</p>';
  view.innerHTML=transcriptHeader(meta,true)+'<div class="val-transcript-detail"><div class="val-detail-main"><section class="val-detail-card"><div class="val-detail-actions"><button class="val-ui-btn primary" onclick="transcriptReviewRecapDraft()">Review Recap Draft</button><button class="val-ui-btn" onclick="transcriptRegenerateRecapDraft()">Regenerate Recap Draft</button><button class="val-ui-btn" onclick="transcriptAskFocus()">Ask VAL About This Transcript</button></div><h3>Processing Status</h3><p>'+safe(status)+'</p><h3>Summary</h3><p>'+safe(s.executiveSummary||'Summary pending.')+'</p><h3>Key Points</h3>'+detailList([s.clientSummary,s.internalNotes].concat(s.relationshipUpdates||[]).filter(Boolean),'No key points extracted.')+'<h3>Decisions</h3>'+detailList(s.keyDecisions,'No decisions extracted.')+'<h3>Action Items</h3>'+detailList(tasks,'No action items extracted.')+'<h3>Created Tasks</h3>'+detailList(createdTasks,'No tasks have been pushed to the main task system yet.')+'<h3>Recap Draft</h3>'+recapHtml+'</section><section class="val-detail-card"><h3>Full Transcript</h3><p class="val-full-transcript">'+safe(t.transcriptText||t.rawTranscript||'No transcript text is available.')+'</p></section></div><aside class="val-detail-side"><section class="val-detail-card"><h3>Participants & Match Confidence</h3>'+detailList(participants,'No participants detected.')+'</section><section class="val-detail-card"><h3>Contact Updates</h3>'+detailList(updates,'No contact updates extracted.')+'</section><section class="val-detail-card"><h3>Action Log</h3>'+detailList(log,'No actions logged.')+'</section><section class="val-detail-card"><h3>Ask VAL About This Transcript</h3><div class="val-chat-log" id="valTranscriptChat"><div class="val-chat-msg">Ask about decisions, commitments, evidence, or relationship context.</div></div><div class="val-chat-input"><input id="valTranscriptQuestion" placeholder="Ask VAL about this transcript" onkeydown="if(event.key===\'Enter\')transcriptAsk()"><button class="val-ui-btn primary" onclick="transcriptAsk()">Ask</button></div></section></aside></div>';
}
function transcriptApproval(path,body){return fetch((window.PROXY||'')+path,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})}).then(function(r){return r.json().then(function(d){if(!r.ok||d.ok===false)throw new Error(d.error||'Approval failed');return d;});});}
window.approveTranscriptTask=function(id){transcriptApproval('/api/val/transcripts/tasks/'+encodeURIComponent(id)+'/approve').then(function(){renderTranscriptReviewQueue();loadTranscripts(false);call('valTasksLoad');}).catch(function(e){alert(e.message);});};
window.approveTranscriptParticipant=function(id){var existing=null;transcriptState.items.some(function(t){existing=(t.participants||[]).find(function(p){return p.participantId===id;});return !!existing;});var contactId=existing&&existing.matchedContactId||prompt('Enter the exact CRM contact ID for this participant:');if(!contactId)return;var contactName=existing&&existing.matchedContactName||prompt('Enter the confirmed contact name:')||'';transcriptApproval('/api/val/transcripts/participants/'+encodeURIComponent(id)+'/approve',{contactId:contactId,contactName:contactName}).then(renderTranscriptReviewQueue).catch(function(e){alert(e.message);});};
window.approveTranscriptContactUpdate=function(id){transcriptApproval('/api/val/transcripts/contact-updates/'+encodeURIComponent(id)+'/approve').then(renderTranscriptReviewQueue).catch(function(e){alert(e.message);});};
function chatMessage(text,user){var log=document.getElementById('valTranscriptChat');if(!log)return;var el=document.createElement('div');el.className='val-chat-msg'+(user?' user':'');el.textContent=text;log.appendChild(el);log.scrollTop=log.scrollHeight;}
window.transcriptAsk=function(question){
  var t=transcriptState.active;if(!t)return;var input=document.getElementById('valTranscriptQuestion'),q=question||(input&&input.value.trim());if(!q)return;if(input)input.value='';chatMessage(q,true);chatMessage('Working from this transcript…',false);var log=document.getElementById('valTranscriptChat'),pending=log&&log.lastChild;
  var context='Use only this selected transcript as the primary context. Transcript title: '+t.title+'\nRelated contact: '+(t.contactName||'not linked')+'\nTranscript ID: '+t.id+'\n\nTRANSCRIPT:\n'+String(t.transcriptText||'').slice(0,14000)+'\n\nUSER REQUEST:\n'+q;
  fetch((window.PROXY||'')+'/api/val/chat',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:context}],dashboard:window.dashData||{}})}).then(function(r){return r.json();}).then(function(d){if(pending)pending.remove();chatMessage((d.message&&d.message.content)||d.message||'No response was returned.',false);if(d.createdTasks&&d.createdTasks.length)call('valTasksLoad');}).catch(function(e){if(pending)pending.remove();chatMessage('Unable to complete that request: '+e.message,false);});
};
function transcriptById(id){return transcriptState.items.find(function(t){return String(t.id)===String(id);})||transcriptState.active;}
function transcriptAction(id,action){return fetch((window.PROXY||'')+'/api/val/transcripts/'+encodeURIComponent(id)+'/actions',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:action})}).then(function(r){return r.json().catch(function(){return{};}).then(function(data){if(!r.ok||data.ok===false)throw new Error(data.error||'Transcript action failed.');return data;});});}
window.transcriptAskFromList=function(id){return openTranscriptDetail(id).then(function(){transcriptAsk('What matters most in this transcript, and what should happen next?');}).catch(function(){});};
window.transcriptCreateTask=function(id){var t=transcriptById(id);if(!t)return;return transcriptAction(t.id,'create_task').then(function(data){if(transcriptState.active&&String(transcriptState.active.id)===String(t.id))chatMessage('Task created: '+data.task.title,false);else if(typeof addSys==='function')addSys('Task created from '+t.title+': '+data.task.title);call('valTasksLoad');}).catch(function(e){if(transcriptState.active)chatMessage('Task was not created: '+e.message,false);else if(typeof addSys==='function')addSys('Task was not created: '+e.message);});};
window.transcriptDraftFollowUp=function(id){var t=transcriptById(id);if(!t)return;return transcriptAction(t.id,'draft_followup').then(function(data){var message='Draft saved for approval.\n\nSubject: '+data.draft.subject+'\n\n'+data.draft.body;if(transcriptState.active&&String(transcriptState.active.id)===String(t.id))chatMessage(message,false);else{if(typeof addSys==='function')addSys('Follow-up draft saved for '+t.title+'.');openTranscriptDetail(t.id).then(function(){chatMessage(message,false);});}}).catch(function(e){if(transcriptState.active)chatMessage('Follow-up draft failed: '+e.message,false);else if(typeof addSys==='function')addSys('Follow-up draft failed: '+e.message);});};
window.transcriptReviewRecapDraft=function(){var t=transcriptState.active;if(!t)return;if(typeof openDraftsPage==='function')openDraftsPage();};
window.transcriptRegenerateRecapDraft=function(){var t=transcriptState.active;if(!t)return;transcriptDraftFollowUp(t.id).then(function(){loadDraftSignals(false);openTranscriptDetail(t.id);});};
window.transcriptAskFocus=function(){var input=document.getElementById('valTranscriptQuestion');if(input){input.focus();input.scrollIntoView({behavior:'smooth',block:'center'});}else transcriptAsk('What should I know and do from this transcript?');};
window.transcriptMarkReviewed=function(){var t=transcriptState.active;if(!t)return;transcriptAction(t.id,'mark_reviewed').then(function(){t.reviewStatus='reviewed';t.status='reviewed';chatMessage('Marked reviewed.',false);loadTranscripts(false).catch(function(){});}).catch(function(e){chatMessage('Could not mark reviewed: '+e.message,false);});};
var originalSend=window.sendMessage;window.sendMessage=function(){var input=document.getElementById('msgInput');if(transcriptState.active&&document.getElementById('valTranscriptView')&&document.getElementById('valTranscriptView').classList.contains('open')&&input&&input.value.trim()){var q=input.value.trim();input.value='';input.style.height='auto';transcriptAsk(q);return;}return originalSend&&originalSend.apply(window,arguments);};
document.addEventListener('click',function(e){var nav=document.getElementById('valPrimaryNav');if(nav&&nav.classList.contains('open')&&!nav.contains(e.target)&&!e.target.closest('.val-mobile-nav'))nav.classList.remove('open');});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installShell);else installShell();
setTimeout(buildCommandCenter,1200);setTimeout(buildCommandCenter,3500);
setInterval(function(){if(!document.getElementById('valTranscriptView')?.classList.contains('open'))buildCommandCenter();},15000);
})();
